name: compilers

on: [push, pull_request]

env:
  cache-suffix: v11
  build_flags: "-DWITH_COMMON=OFF -DWITH_THREAD=ON -DWITH_WERROR=ON -DWITH_EXTRA_WARNINGS=ON"


jobs:
  

  windows-latest-mingw:
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v4.1.1
      - name : Build
        run: |
            cmake -Bbuild -G "MinGW Makefiles" -DWITH_SELFCONTAINED=ON -DWITH_FATROP=ON -DWITH_BUILD_FATROP=ON -DWITH_BUILD_REQUIRED=ON -DCMAKE_INSTALL_PREFIX=install ${{env.build_flags}}
            cmake --build build --target install --config Release -v
